apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shell-job.fullname" . }}
  labels:
    {{- include "shell-job.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "script.zsh").AsConfig | indent 2 }}

